### ISSUE TITLE
toast.push 위치 질문입니다.

### ISSUE THREAD

**Issue by llois** [axisj-com/axisj#415]
안녕하세요? 좋은 프로그램 감사드립니다.

제가 관련 문서를 못찾는지는 모르겠는데

toast.push로 메세지창을 띄울때, 항상 오른쪽 윗쪽으로 고정이 되는데

혹시 이 위치를 변경이 가능한건가요?

언제나 감사합니다^^

**Comment by tom-axisj** [comment]
```css
.AXNotificationTray {
  position: fixed;
  right: 10px;
  top: 0;
  z-index: 5001;
  width: 322px;
}
```

이런 css 가 있습니다. AXJ.min.css 에
이걸 재 선언 해보세요. 단 left로 하시려면 right:auto 로 클리어 하시고 left를 지정하세요.
